from .academic_record_view import Academic_recordList
from .academic_record_view import Academic_recordDetail
from .professoral_record_view import Professoral_recordList
from .professoral_record_view import Professoral_recordDetail